/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group7.ecobikerentalgroup7.boundary.admin;

import com.hust.group7.ecobikerentalgroup7.Constants;
import com.hust.group7.ecobikerentalgroup7.DataBase;
import com.hust.group7.ecobikerentalgroup7.Entity.Bike;
import com.hust.group7.ecobikerentalgroup7.Entity.Station;
import com.hust.group7.ecobikerentalgroup7.Entity.Transaction;
import com.hust.group7.ecobikerentalgroup7.Entity.User;
import com.hust.group7.ecobikerentalgroup7.MainEntry;
import com.hust.group7.ecobikerentalgroup7.boundary.HomeScreen;
import com.hust.group7.ecobikerentalgroup7.boundary.LoginScreen;
import static com.hust.group7.ecobikerentalgroup7.boundary.HomeScreen.user;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AdminHomeScreen extends javax.swing.JFrame {

	/**
	 * Creates new form HomeScreen
	 */
	private DataBase db;
	public static User user;
	private JFrame backScreen;
	private Transaction transaction;
	private Bike bike;

	public AdminHomeScreen(User user, JFrame backScreen) throws SQLException {
		initComponents();
		this.user = user;
		this.backScreen = backScreen;
		this.db = new DataBase();
		imageCodePanel.showImage(new File("home_station.jpg"));
		usernameLabel.setText(user.getUsername());
	}

	private void getTransaction() throws SQLException {
		int bikeId;
		String sqlGetTransaction = "SELECT * FROM transactions WHERE user_id = '" + user.getUserId() + "'";
		ResultSet rs = db.query(sqlGetTransaction);
		while (rs.next()) {
			transaction = new Transaction();
			transaction.setTransactionId(rs.getInt("id"));
			transaction.setBikeId(rs.getInt("bike_id"));
			transaction.setUserId(rs.getInt("user_id"));
			transaction.setStartTime(rs.getString("start_time"));
			transaction.setEndTime(rs.getString("end_time"));
			transaction.setPaymentMethodId(rs.getInt("payment_method_id"));
			transaction.setStatus(rs.getInt("status"));
			transaction.setDescription(rs.getString("description"));
			transaction.setDeposit(rs.getFloat("deposit"));
			
		
			
			String sqlGetBike = "SELECT * FROM bikes WHERE id = '" + transaction.getBikeId() + "'";
			System.out.println("bike_id_transaction===>" + transaction.getBikeId());
			ResultSet rs2 = db.query(sqlGetBike);
			bike = new Bike();
			while (rs2.next()) {
				Bike bike = new Bike();
				bike.setBikeId(rs2.getInt("id"));
				bike.setName(rs2.getString("name"));
				bike.setType(rs2.getString("type"));
				bike.setWeight(rs2.getFloat("weight"));
				bike.setLicensePlate(rs2.getString("license_plate"));
				bike.setManufacturingDate(rs2.getString("type"));
				bike.setProducer(rs2.getString("producer"));
				bike.setBarcode(rs2.getString("barcode"));
				bike.setStationId(rs2.getInt("station_id"));
				bike.setImage(rs2.getString("image"));
				bike.setStatus(rs2.getInt("status"));
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		logoutButton = new javax.swing.JButton();
		usernameLabel = new javax.swing.JLabel();
		imageCodePanel = new com.hust.group7.ecobikerentalgroup7.boundary.ImageCodePanel();
		jLabel3 = new javax.swing.JLabel();
		btnManageStation = new javax.swing.JButton();
		btnManageBike = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Home");
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("ECO BIKE RENTAL");

		jLabel2.setText("GROUP 7");

		logoutButton.setText("Log out");
		logoutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutButtonActionPerformed(evt);
			}
		});

		usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		usernameLabel.setText("Admin");

		javax.swing.GroupLayout imageCodePanelLayout = new javax.swing.GroupLayout(imageCodePanel);
		imageCodePanel.setLayout(imageCodePanelLayout);
		imageCodePanelLayout.setHorizontalGroup(imageCodePanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 334, Short.MAX_VALUE));
		imageCodePanelLayout.setVerticalGroup(imageCodePanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 171, Short.MAX_VALUE));

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel3.setText("ADMIN HOME PAGE");

		btnManageStation.setText("Manage Station");
		btnManageStation.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnManageStationActionPerformed(evt);
			}
		});

		btnManageBike.setText("Manage Bike");
		btnManageBike.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnManageBikeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(69, 69, 69)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2).addComponent(jLabel1))
										.addGap(130, 130, 130).addComponent(jLabel3).addGap(107, 107, 107)
										.addComponent(usernameLabel).addGap(37, 37, 37).addComponent(logoutButton))
								.addGroup(layout.createSequentialGroup().addGap(181, 181, 181).addComponent(
										imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(210, 210, 210)
										.addComponent(btnManageStation).addGap(57, 57, 57).addComponent(btnManageBike)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(38, 38, 38)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(logoutButton).addComponent(usernameLabel).addComponent(jLabel3))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2)
				.addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnManageStation).addComponent(btnManageBike))
				.addGap(18, 18, 18)
				.addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(80, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutButtonActionPerformed
		int confirm = JOptionPane.showConfirmDialog(this, "Are you sure");
		System.out.println("confirm: " + confirm);
		if (confirm == JOptionPane.YES_OPTION) {
			MainEntry.move(this, new LoginScreen());
		}
	}// GEN-LAST:event_logoutButtonActionPerformed

	private void btnManageStationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnManageStationActionPerformed
		// TODO add your handling code here:
		try {
			MainEntry.move(this, new AdminManageStation(user, this));
		} catch (SQLException ex) {
			Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnManageStationActionPerformed

	private void btnManageBikeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnManageBikeActionPerformed
		try {
			// TODO add your handling code here:
			Station st = new Station();
			st.setStationId(-1);
			MainEntry.move(this, new AdminManageBikes(this, user, st));
		} catch (SQLException ex) {
			Logger.getLogger(AdminHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnManageBikeActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnManageBike;
	private javax.swing.JButton btnManageStation;
	private com.hust.group7.ecobikerentalgroup7.boundary.ImageCodePanel imageCodePanel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton logoutButton;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration//GEN-END:variables
}
