/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group7.ecobikerentalgroup7.boundary.admin;

import com.hust.group7.ecobikerentalgroup7.Constants;
import com.hust.group7.ecobikerentalgroup7.DataBase;
import com.hust.group7.ecobikerentalgroup7.Entity.Bike;
import com.hust.group7.ecobikerentalgroup7.Entity.Station;
import com.hust.group7.ecobikerentalgroup7.Entity.User;

import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import com.hust.group7.ecobikerentalgroup7.MainEntry;
import java.io.File;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileSystemView;
import jdk.nashorn.internal.objects.NativeArray;

public class AdminAddBike extends javax.swing.JFrame {

    /**
     * Creates new form FindStationScreen
     */
    File fileBarCode;
    private JFrame backScreen;
    private ArrayList<Station> arrStation;
    private DataBase db;
    private User user;
    private Station passStation;

    public AdminAddBike(User user, JFrame backScreen) throws SQLException {
        initComponents();
        this.backScreen = backScreen;
        this.db = new DataBase();
        this.user = user;
        addStation();
    }

    public void addStation() {
        arrStation = new ArrayList<>();
        try {
            String sqlString = "select * from stations";
            ResultSet rs = db.query(sqlString);
            while (rs.next()) {
                Station station = new Station();
                station.setAddress(rs.getString("address"));
                station.setStationId(rs.getInt("id"));
                station.setName(rs.getString("name"));
                station.setDistance(rs.getInt("distance_to_walk"));
                arrStation.add(station);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        for (Station x : arrStation) {
            cbbStation.addItem(x.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        btnCancel = new javax.swing.JButton();
        btnAddBike = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfProducer = new javax.swing.JTextField();
        tfPlateLiscense = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfBarcode = new javax.swing.JTextField();
        tfBattery = new javax.swing.JTextField();
        cbbStation = new javax.swing.JComboBox<>();
        tfWeight = new javax.swing.JTextField();
        cbbBikeType = new javax.swing.JComboBox<>();
        dcManufacturingDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnAddBikeImage = new javax.swing.JButton();
        imageCodePanel = new com.hust.group7.ecobikerentalgroup7.boundary.ImageCodePanel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Bike");
        setResizable(false);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddBike.setText("Add");
        btnAddBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBikeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADD BIKE");

        jLabel6.setText("Station :");

        jLabel7.setText("Plate Liscense :");

        jLabel8.setText("Weight :");

        jLabel9.setText("Producer :");

        jLabel10.setText("Battery :");

        jLabel11.setText("Manufacturing Date :");

        jLabel12.setText("Bike Type :");

        jLabel1.setText("Barcode :");

        cbbBikeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bike", "EBike", "Twin Bike" }));

        dcManufacturingDate.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Image :");

        btnAddBikeImage.setText("Add Image");
        btnAddBikeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBikeImageActionPerformed(evt);
            }
        });

        imageCodePanel.setPreferredSize(new java.awt.Dimension(178, 178));

        javax.swing.GroupLayout imageCodePanelLayout = new javax.swing.GroupLayout(imageCodePanel);
        imageCodePanel.setLayout(imageCodePanelLayout);
        imageCodePanelLayout.setHorizontalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        imageCodePanelLayout.setVerticalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jLabel3.setText("Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfProducer)
                                .addComponent(tfPlateLiscense, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3))
                        .addGap(178, 178, 178))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddBikeImage)
                            .addComponent(dcManufacturingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(31, 31, 31)
                                .addComponent(btnAddBike, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(tfBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(cbbBikeType, 0, 1, Short.MAX_VALUE)
                    .addComponent(tfBattery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbbStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPlateLiscense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbbBikeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfProducer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfBattery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcManufacturingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBikeImage)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBike)
                    .addComponent(btnCancel))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBikeActionPerformed

        DateFormat fm = new SimpleDateFormat("yyyy/MM/dd");

        String station = cbbStation.getSelectedItem().toString();
        String name = tfName.getText(),
                plateLiscense = tfPlateLiscense.getText(),
                producer = tfProducer.getText(),
                weight = tfWeight.getText(),
                imageName = imageCodePanel.getImageName(),
                bikeType = cbbBikeType.getSelectedItem().toString(),
                battery = tfBattery.getText(),
                barCode = tfBarcode.getText(),
                manufacturingDate = fm.format(dcManufacturingDate.getDate());

        for (Station x : arrStation) {
            if (x.getName().equals(station)) {
                String sqlGetBikeAvailable = "select * from bikes  where station_id='" + x.getStationId() + "' and status='0'";
                //add Bike
                String sql = "INSERT INTO `bikes` (`id`, `name`, `type`, `weight`, `license_plate`, `manuafacturing_date`, `producer`, `batery_percentage`, `load_cycles`, `time_remaining`, `barcode`,`status`, `station_id`, `image`) VALUES\n"
                        + "(null, '" + name
                        + "','" + bikeType
                        + "',' " + weight
                        + "', '" + plateLiscense
                        + "', '" + manufacturingDate
                        + "', '" + producer
                        + "', '" + battery
                        + "',null, null, '" + barCode
                        + "', 0,'" + getStationIDByName(station)
                        + "', '" + imageName + "')";
                try {
                    db.insert(sql);
                    JOptionPane.showMessageDialog(this, "Inserted!");
                    // -------------------
                    String sqlString = "select * from stations where name= '" + station + "';";
                    ResultSet rs = db.query(sqlString);
                    Station stationBack = new Station();
                    while (rs.next()) {
                        
                        stationBack.setAddress(rs.getString("address"));
                        stationBack.setStationId(rs.getInt("id"));
                        stationBack.setName(rs.getString("name"));
                        stationBack.setDistance(rs.getInt("distance_to_walk"));
                        
                    }
                    
                    // ---------------
                    MainEntry.move(this, new AdminManageBikes(new AdminHomeScreen(user, null), user, stationBack));
//            showInfoTable();
                } catch (SQLException ex) {
                    Logger.getLogger(AdminAddStation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnAddBikeActionPerformed

    private void btnAddBikeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBikeImageActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        File wd = new File(System.getProperty("user.dir"));
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.setCurrentDirectory(wd);
        int r = jfc.showSaveDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            //addFileLabel.setText(jfc.getSelectedFile().getName());
            fileBarCode = jfc.getSelectedFile();
            imageCodePanel.showImage(jfc.getSelectedFile());
            imageCodePanel.repaint();
        } else {
            //addFileLabel.setText("You choose no file");
        }
    }//GEN-LAST:event_btnAddBikeImageActionPerformed

    private int getStationIDByName(String stationName) {
        int ID = -1;
        for (Station x : arrStation) {
            if (x.getName().equals(stationName)) {
                ID = x.getStationId();
                break;
            }
        }
        return ID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBike;
    private javax.swing.JButton btnAddBikeImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbbBikeType;
    private javax.swing.JComboBox<String> cbbStation;
    private com.toedter.calendar.JDateChooser dcManufacturingDate;
    private com.hust.group7.ecobikerentalgroup7.boundary.ImageCodePanel imageCodePanel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfBarcode;
    private javax.swing.JTextField tfBattery;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPlateLiscense;
    private javax.swing.JTextField tfProducer;
    private javax.swing.JTextField tfWeight;
    // End of variables declaration//GEN-END:variables
}
