/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group7.ecobikerentalgroup7.boundary;

import com.google.zxing.FormatException;
import com.hust.group7.ecobikerentalgroup7.Constants;
import com.hust.group7.ecobikerentalgroup7.DataBase;
import com.hust.group7.ecobikerentalgroup7.Entity.Bike;
import com.hust.group7.ecobikerentalgroup7.Entity.Cost;
import com.hust.group7.ecobikerentalgroup7.Entity.Transaction;
import com.hust.group7.ecobikerentalgroup7.Entity.User;
import com.hust.group7.ecobikerentalgroup7.MainEntry;
import com.hust.group7.ecobikerentalgroup7.controller.RentBikeController;
import com.hust.group7.ecobikerentalgroup7.controller.ReturnBikeController;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

public class EnterCodeScreen extends javax.swing.JFrame {

    /**
     * Creates new form RentBikeScreen
     */
    private JFrame backScreen;
    private User user;
    public RentBikeController rentBikeController;
    public ReturnBikeController returnBikeController;
    private Transaction transaction;
    private DataBase db = new DataBase();

    public EnterCodeScreen(User user, Transaction trans, JFrame backScreen) throws SQLException {
        initComponents();
        this.transaction = trans;
        this.user = user;
        this.backScreen = backScreen;
        rentBikeController = new RentBikeController();
    }

   

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRent = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfBikeBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scan Code");
        setResizable(false);

        btnRent.setText("Rent");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Bike Barcode :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfBikeBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(btnRent)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBikeBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRent)
                    .addComponent(backBtn))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        String code = tfBikeBarCode.getText();
        String sql = "SELECT * FROM bikes WHERE barcode = '" + code + "'";
        try {
            ResultSet rs = db.query(sql);
            
            if (rs.next() == true) {
                Bike bike = new Bike();
                bike.setBikeId(rs.getInt("id"));
                bike.setName(rs.getString("name"));
                
                bike.setType(rs.getString("type"));
                sql = "SELECT * FROM cost WHERE bike_type = '" + bike.getType() + "'";
                ResultSet rs2 = db.query(sql);
                rs2.next();
                Cost cost = new Cost();
                cost.setDeposit(rs2.getFloat("deposit"));
                cost.setType(rs2.getString("bike_type"));
                cost.set_15mLater(rs2.getFloat("15m_later"));
                cost.set_30mFirst(rs2.getFloat("30m_first"));
                        
                bike.setCost(cost);
                bike.setWeight(rs.getFloat("weight"));
                bike.setLicensePlate(rs.getString("license_plate"));
                bike.setManufacturingDate(rs.getString("manuafacturing_date"));
                bike.setProducer(rs.getString("producer"));
                bike.setBarcode(rs.getString("barcode"));
                bike.setBateryPercentage(rs.getString("batery_percentage"));
                bike.setLoadCycles(rs.getString("load_cycles"));
                bike.setTimeRemaining(rs.getString("time_remaining"));
                bike.setStationId(rs.getInt("station_id"));
                bike.setImage(rs.getString("image"));
                bike.setStatus(rs.getInt("status"));
                try {
                    MainEntry.move(this, new PaymentScreen(user, bike, backScreen));
                } catch (Exception ex) {
                    Logger.getLogger(EnterCodeScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No bike matched!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EnterCodeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRentActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnRent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfBikeBarCode;
    // End of variables declaration//GEN-END:variables
}
